<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Libr4.Auth.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Libr4.Auth.Domain\Libr4.Auth.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Libr4.Shared.Kernel\Libr4.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\Libr4.Shared.Contracts\Libr4.Shared.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
