namespace Libr4.Shared.Contracts.Artifacts;

/// <summary>
/// Interface for generating artifacts during agent execution.
/// Artifacts are tangible deliverables that provide structured output
/// instead of raw tool calls.
/// </summary>
public interface IArtifactGenerator
{
    /// <summary>
    /// Generates a task list artifact from unstructured task data.
    /// </summary>
    /// <param name="title">Title of the task list.</param>
    /// <param name="tasks">Unstructured task data (e.g., from LLM output).</param>
    /// <param name="generatedBy">ID of the agent that generated this artifact.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The generated task list artifact.</returns>
    Task<TaskListArtifact> GenerateTaskListAsync(
        string title,
        string tasks,
        string? generatedBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Generates an implementation plan artifact from unstructured plan data.
    /// </summary>
    /// <param name="title">Title of the implementation plan.</param>
    /// <param name="planData">Unstructured plan data (e.g., from LLM output).</param>
    /// <param name="generatedBy">ID of the agent that generated this artifact.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The generated implementation plan artifact.</returns>
    Task<ImplementationPlanArtifact> GenerateImplementationPlanAsync(
        string title,
        string planData,
        string? generatedBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Generates a screenshot artifact from image data.
    /// </summary>
    /// <param name="imageData">Base64-encoded image data.</param>
    /// <param name="imageFormat">Image format (e.g., "png", "jpeg").</param>
    /// <param name="annotation">Optional annotation or description.</param>
    /// <param name="sourceUrl">Optional URL where the screenshot was captured.</param>
    /// <param name="generatedBy">ID of the agent that generated this artifact.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The generated screenshot artifact.</returns>
    Task<ScreenshotArtifact> GenerateScreenshotAsync(
        string imageData,
        string imageFormat = "png",
        string? annotation = null,
        string? sourceUrl = null,
        string? generatedBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Generates a browser recording artifact from recording data.
    /// </summary>
    /// <param name="recordingUrl">URL to the recording file.</param>
    /// <param name="format">Recording format (e.g., "webm", "mp4").</param>
    /// <param name="durationSeconds">Duration of the recording in seconds.</param>
    /// <param name="fileSizeBytes">File size in bytes.</param>
    /// <param name="steps">Steps or actions performed in the recording.</param>
    /// <param name="generatedBy">ID of the agent that generated this artifact.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The generated browser recording artifact.</returns>
    Task<BrowserRecordingArtifact> GenerateBrowserRecordingAsync(
        string recordingUrl,
        string format = "webm",
        int durationSeconds = 0,
        long fileSizeBytes = 0,
        List<string>? steps = null,
        string? generatedBy = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Adds a comment to an artifact.
    /// </summary>
    /// <param name="artifactId">ID of the artifact.</param>
    /// <param name="userId">ID of the user making the comment.</param>
    /// <param name="userName">Username of the commenter.</param>
    /// <param name="text">Comment text.</param>
    /// <param name="requiresAction">Whether the comment requires agent action.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The updated artifact.</returns>
    Task<Artifact> AddCommentAsync(
        string artifactId,
        string userId,
        string userName,
        string text,
        bool requiresAction = false,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets an artifact by ID.
    /// </summary>
    /// <param name="artifactId">ID of the artifact.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The artifact, or null if not found.</returns>
    Task<Artifact?> GetArtifactAsync(
        string artifactId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all artifacts generated by a specific agent or task.
    /// </summary>
    /// <param name="generatedBy">ID of the generator.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>List of artifacts.</returns>
    Task<IReadOnlyList<Artifact>> GetArtifactsByGeneratorAsync(
        string generatedBy,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates the status of an artifact.
    /// </summary>
    /// <param name="artifactId">ID of the artifact.</param>
    /// <param name="status">New status.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The updated artifact.</returns>
    Task<Artifact> UpdateStatusAsync(
        string artifactId,
        ArtifactStatus status,
        CancellationToken cancellationToken = default);
}
