<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DevOpsAlgorithms.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Libr4.Shared.Kernel\Libr4.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\AI\Libr4.AI.Infrastructure\Libr4.AI.Infrastructure.csproj" />
    <ProjectReference Include="../../AI/Libr4.AI.Application/Libr4.AI.Application.csproj" />
    <ProjectReference Include="..\Libr4.DevOps.Domain\Libr4.DevOps.Domain.csproj" />
  </ItemGroup>

</Project>