<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="AspNetCoreRateLimit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libr4.Auth.Application\Libr4.Auth.Application.csproj" />
    <ProjectReference Include="..\Libr4.Auth.Domain\Libr4.Auth.Domain.csproj" />
    <ProjectReference Include="..\Libr4.Auth.Infrastructure\Libr4.Auth.Infrastructure.csproj" />
  </ItemGroup>
</Project>
