<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Libr4.Trading.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Libr4.Shared.Web\Libr4.Shared.Web.csproj" />
    <ProjectReference Include="..\Libr4.Trading.Application\Libr4.Trading.Application.csproj" />
    <ProjectReference Include="..\Libr4.Trading.Infrastructure\Libr4.Trading.Infrastructure.csproj" />
    <ProjectReference Include="..\Libr4.Trading.Domain\Libr4.Trading.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>
</Project>
