namespace Libr4.Shared.Contracts.PlanAgent;

/// <summary>
/// Represents a plan generated by the plan agent.
/// </summary>
public record AgentPlan
{
    /// <summary>
    /// Unique identifier for the plan.
    /// </summary>
    public string Id { get; init; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Plan name.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// Plan description.
    /// </summary>
    public string Description { get; init; } = string.Empty;

    /// <summary>
    /// User request that generated this plan.
    /// </summary>
    public string UserRequest { get; init; } = string.Empty;

    /// <summary>
    /// Plan steps.
    /// </summary>
    public List<PlanStep> Steps { get; init; } = new();

    /// <summary>
    /// Estimated duration in hours.
    /// </summary>
    public int? EstimatedHours { get; init; }

    /// <summary>
    /// Plan complexity score (0-1).
    /// </summary>
    public double Complexity { get; init; }

    /// <summary>
    /// When the plan was created.
    /// </summary>
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Plan status.
    /// </summary>
    public PlanStatus Status { get; init; } = PlanStatus.Draft;

    /// <summary>
    /// Plan metadata.
    /// </summary>
    public Dictionary<string, string> Metadata { get; init; } = new();
}

/// <summary>
/// Status of a plan.
/// </summary>
public enum PlanStatus
{
    Draft,
    Reviewing,
    Approved,
    Rejected,
    Executing,
    Completed,
    Failed
}

/// <summary>
/// Represents a step in a plan.
/// </summary>
public record PlanStep
{
    /// <summary>
    /// Unique identifier for the step.
    /// </summary>
    public string Id { get; init; } = Guid.NewGuid().ToString();

    /// <summary>
    /// Step name.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// Step description.
    /// </summary>
    public string Description { get; init; } = string.Empty;

    /// <summary>
    /// Step order.
    /// </summary>
    public int Order { get; init; }

    /// <summary>
    /// Agent or skill to execute this step.
    /// </summary>
    public string? AssignedAgent { get; init; }

    /// <summary>
    /// Dependencies on other step IDs.
    /// </summary>
    public List<string> DependsOn { get; init; } = new();

    /// <summary>
    /// Estimated duration in minutes.
    /// </summary>
    public int? EstimatedMinutes { get; init; }

    /// <summary>
    /// Step status.
    /// </summary>
    public StepStatus Status { get; init; } = StepStatus.Pending;

    /// <summary>
    /// Step output or result.
    /// </summary>
    public string? Output { get; init; }
}

/// <summary>
/// Status of a step.
/// </summary>
public enum StepStatus
{
    Pending,
    InProgress,
    Completed,
    Failed,
    Skipped
}

/// <summary>
/// Interface for plan agent service.
/// Provides an additional planning layer if the current planner doesn't cover scenarios.
/// </summary>
public interface IPlanAgent
{
    /// <summary>
    /// Generates a plan from a user request.
    /// </summary>
    /// <param name="userRequest">User request.</param>
    /// <param name="context">Additional context for planning.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Generated plan.</returns>
    Task<AgentPlan> GeneratePlanAsync(
        string userRequest,
        PlanContext? context = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Refines an existing plan.
    /// </summary>
    /// <param name="plan">Plan to refine.</param>
    /// <param name="feedback">Feedback for refinement.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Refined plan.</returns>
    Task<AgentPlan> RefinePlanAsync(
        AgentPlan plan,
        string feedback,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Validates a plan.
    /// </summary>
    /// <param name="plan">Plan to validate.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Validation result.</returns>
    Task<PlanValidationResult> ValidatePlanAsync(
        AgentPlan plan,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a plan by ID.
    /// </summary>
    /// <param name="planId">Plan ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The plan, or null if not found.</returns>
    Task<AgentPlan?> GetPlanAsync(
        string planId,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all plans.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>List of all plans.</returns>
    Task<IReadOnlyList<AgentPlan>> GetAllPlansAsync(
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Context for plan generation.
/// </summary>
public record PlanContext
{
    /// <summary>
    /// Available skills or agents.
    /// </summary>
    public List<string> AvailableSkills { get; init; } = new();

    /// <summary>
    /// Constraints or limitations.
    /// </summary>
    public Dictionary<string, string> Constraints { get; init; } = new();

    /// <summary>
    /// Previous plans or context.
    /// </summary>
    public List<string> PreviousContext { get; init; } = new();

    /// <summary>
    /// User preferences.
    /// </summary>
    public Dictionary<string, string> UserPreferences { get; init; } = new();
}

/// <summary>
/// Result of plan validation.
/// </summary>
public record PlanValidationResult
{
    /// <summary>
    /// Whether the plan is valid.
    /// </summary>
    public bool IsValid { get; init; }

    /// <summary>
    /// Validation errors.
    /// </summary>
    public List<string> Errors { get; init; } = new();

    /// <summary>
    /// Validation warnings.
    /// </summary>
    public List<string> Warnings { get; init; } = new();

    /// <summary>
    /// Validation score (0-1).
    /// </summary>
    public double Score { get; init; }
}

/// <summary>
/// In-memory implementation of plan agent service.
/// </summary>
public class InMemoryPlanAgent : IPlanAgent
{
    private readonly Dictionary<string, AgentPlan> _plans = new();

    public Task<AgentPlan> GeneratePlanAsync(
        string userRequest,
        PlanContext? context = null,
        CancellationToken cancellationToken = default)
    {
        var plan = new AgentPlan
        {
            Name = $"Plan for: {userRequest.Substring(0, Math.Min(50, userRequest.Length))}",
            Description = userRequest,
            UserRequest = userRequest,
            Steps = GenerateSteps(userRequest, context),
            Complexity = CalculateComplexity(userRequest),
            Status = PlanStatus.Draft
        };

        _plans[plan.Id] = plan;
        return Task.FromResult(plan);
    }

    public Task<AgentPlan> RefinePlanAsync(
        AgentPlan plan,
        string feedback,
        CancellationToken cancellationToken = default)
    {
        var refined = plan with
        {
            Description = $"{plan.Description}\n\nRefined based on: {feedback}",
            Status = PlanStatus.Reviewing
        };

        _plans[refined.Id] = refined;
        return Task.FromResult(refined);
    }

    public Task<PlanValidationResult> ValidatePlanAsync(
        AgentPlan plan,
        CancellationToken cancellationToken = default)
    {
        var errors = new List<string>();
        var warnings = new List<string>();

        // Validate plan structure
        if (string.IsNullOrEmpty(plan.Name))
        {
            errors.Add("Plan name is required");
        }

        if (!plan.Steps.Any())
        {
            errors.Add("Plan must have at least one step");
        }

        // Validate step dependencies
        var stepIds = plan.Steps.Select(s => s.Id).ToHashSet();
        foreach (var step in plan.Steps)
        {
            foreach (var dep in step.DependsOn)
            {
                if (!stepIds.Contains(dep))
                {
                    warnings.Add($"Step {step.Id} depends on non-existent step {dep}");
                }
            }
        }

        // Calculate validation score
        var score = errors.Count == 0 ? 1.0 : Math.Max(0, 1.0 - (errors.Count * 0.2));

        return Task.FromResult(new PlanValidationResult
        {
            IsValid = errors.Count == 0,
            Errors = errors,
            Warnings = warnings,
            Score = score
        });
    }

    public Task<AgentPlan?> GetPlanAsync(
        string planId,
        CancellationToken cancellationToken = default)
    {
        _plans.TryGetValue(planId, out var plan);
        return Task.FromResult(plan);
    }

    public Task<IReadOnlyList<AgentPlan>> GetAllPlansAsync(
        CancellationToken cancellationToken = default)
    {
        return Task.FromResult<IReadOnlyList<AgentPlan>>(_plans.Values.ToList().AsReadOnly());
    }

    private static List<PlanStep> GenerateSteps(string userRequest, PlanContext? context)
    {
        // Simple step generation - in production, this would use LLM
        var steps = new List<PlanStep>
        {
            new PlanStep
            {
                Name = "Analyze request",
                Description = "Analyze the user request and understand requirements",
                Order = 1,
                Status = StepStatus.Pending
            },
            new PlanStep
            {
                Name = "Generate solution",
                Description = "Generate a solution based on the analysis",
                Order = 2,
                DependsOn = new List<string>(),
                Status = StepStatus.Pending
            },
            new PlanStep
            {
                Name = "Validate solution",
                Description = "Validate the generated solution",
                Order = 3,
                DependsOn = new List<string>(),
                Status = StepStatus.Pending
            }
        };

        return steps;
    }

    private static double CalculateComplexity(string userRequest)
    {
        // Simple complexity calculation based on request length and keywords
        var complexity = Math.Min(1.0, userRequest.Length / 1000.0);
        
        if (userRequest.Contains("multi", StringComparison.OrdinalIgnoreCase) ||
            userRequest.Contains("complex", StringComparison.OrdinalIgnoreCase))
        {
            complexity += 0.2;
        }

        return Math.Clamp(complexity, 0, 1);
    }
}
