// <auto-generated />
using System;
using Libr4.Matching.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Libr4.Matching.Infrastructure.Migrations
{
    [DbContext(typeof(MatchingDbContext))]
    partial class MatchingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("matching")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Libr4.Matching.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Feedback")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FeedbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("uuid");

                    b.Property<float>("KeywordScore")
                        .HasColumnType("real");

                    b.Property<string>("MatchingSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("SemanticScore")
                        .HasColumnType("real");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<float>("TotalScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Matches", "matching");
                });

            modelBuilder.Entity("Libr4.Matching.Infrastructure.Persistence.ScoringWeightsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BudgetFitWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("ExperienceWeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("KeywordSkillWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("RecencyWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("ReputationWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("SemanticWeight")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ScoringWeights", "matching");
                });
#pragma warning restore 612, 618
        }
    }
}
