<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Libr4.Collaboration.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="AutoMapper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libr4.Collaboration.Domain\Libr4.Collaboration.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Libr4.Shared.Kernel\Libr4.Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
