// <auto-generated />
using System;
using Libr4.Collaboration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Libr4.Collaboration.Infrastructure.Migrations
{
    [DbContext(typeof(CollaborationDbContext))]
    partial class CollaborationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collaboration")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Libr4.Collaboration.Domain.CollaborationRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveCallId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCallId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskId");

                    b.ToTable("rooms", "collaboration");
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.SharedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CollaboratingUsers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CollaborationRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CollaborationRoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("documents", "collaboration");
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.VideoCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollaborationRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRecording")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CollaborationRoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("video_calls", "collaboration");
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.Whiteboard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CollaborationRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollaborationRoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("whiteboards", "collaboration");
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.CollaborationRoom", b =>
                {
                    b.HasOne("Libr4.Collaboration.Domain.VideoCall", "ActiveCall")
                        .WithMany()
                        .HasForeignKey("ActiveCallId");

                    b.OwnsMany("Libr4.Collaboration.Domain.ChatMessage", "Messages", b1 =>
                        {
                            b1.Property<Guid>("CollaborationRoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("EditedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsEdited")
                                .HasColumnType("boolean");

                            b1.Property<Guid?>("ReplyToId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SenderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("SentAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("CollaborationRoomId", "__synthesizedOrdinal");

                            b1.ToTable("rooms", "collaboration");

                            b1.ToJson("Messages");

                            b1.WithOwner()
                                .HasForeignKey("CollaborationRoomId");
                        });

                    b.OwnsOne("Libr4.Collaboration.Domain.CollaborationRoomSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("CollaborationRoomId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowRecording")
                                .HasColumnType("boolean");

                            b1.Property<bool>("AllowScreenShare")
                                .HasColumnType("boolean");

                            b1.Property<bool>("EnableEndToEndEncryption")
                                .HasColumnType("boolean");

                            b1.Property<int>("MaxParticipants")
                                .HasColumnType("integer");

                            b1.Property<bool>("RequireApprovalForJoin")
                                .HasColumnType("boolean");

                            b1.HasKey("CollaborationRoomId");

                            b1.ToTable("rooms", "collaboration");

                            b1.ToJson("Settings");

                            b1.WithOwner()
                                .HasForeignKey("CollaborationRoomId");
                        });

                    b.OwnsMany("Libr4.Collaboration.Domain.CollaborationSession", "Sessions", b1 =>
                        {
                            b1.Property<Guid>("CollaborationRoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("LeftAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("CollaborationRoomId", "__synthesizedOrdinal");

                            b1.ToTable("rooms", "collaboration");

                            b1.ToJson("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("CollaborationRoomId");
                        });

                    b.OwnsMany("Libr4.Collaboration.Domain.FileShare", "FileShares", b1 =>
                        {
                            b1.Property<Guid>("CollaborationRoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint");

                            b1.Property<string>("FileType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FileUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("CollaborationRoomId", "__synthesizedOrdinal");

                            b1.ToTable("rooms", "collaboration");

                            b1.ToJson("FileShares");

                            b1.WithOwner()
                                .HasForeignKey("CollaborationRoomId");
                        });

                    b.OwnsMany("Libr4.Collaboration.Domain.Participant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("CollaborationRoomId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Role")
                                .HasColumnType("integer");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("CollaborationRoomId", "__synthesizedOrdinal");

                            b1.ToTable("rooms", "collaboration");

                            b1.ToJson("Participants");

                            b1.WithOwner()
                                .HasForeignKey("CollaborationRoomId");
                        });

                    b.Navigation("ActiveCall");

                    b.Navigation("FileShares");

                    b.Navigation("Messages");

                    b.Navigation("Participants");

                    b.Navigation("Sessions");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.SharedDocument", b =>
                {
                    b.HasOne("Libr4.Collaboration.Domain.CollaborationRoom", null)
                        .WithMany("Documents")
                        .HasForeignKey("CollaborationRoomId");

                    b.OwnsOne("Libr4.Collaboration.Domain.DocumentPermissions", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("SharedDocumentId")
                                .HasColumnType("uuid");

                            b1.HasKey("SharedDocumentId");

                            b1.ToTable("documents", "collaboration");

                            b1.ToJson("Permissions");

                            b1.WithOwner()
                                .HasForeignKey("SharedDocumentId");
                        });

                    b.OwnsMany("Libr4.Collaboration.Domain.DocumentVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("SharedDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Version")
                                .HasColumnType("integer");

                            b1.HasKey("SharedDocumentId", "__synthesizedOrdinal");

                            b1.ToTable("documents", "collaboration");

                            b1.ToJson("Versions");

                            b1.WithOwner()
                                .HasForeignKey("SharedDocumentId");
                        });

                    b.Navigation("Permissions")
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.VideoCall", b =>
                {
                    b.HasOne("Libr4.Collaboration.Domain.CollaborationRoom", null)
                        .WithMany("VideoCalls")
                        .HasForeignKey("CollaborationRoomId");

                    b.OwnsMany("Libr4.Collaboration.Domain.CallParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("VideoCallId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("VideoCallId", "__synthesizedOrdinal");

                            b1.ToTable("video_calls", "collaboration");

                            b1.ToJson("Participants");

                            b1.WithOwner()
                                .HasForeignKey("VideoCallId");
                        });

                    b.OwnsMany("Libr4.Collaboration.Domain.CallRecording", "Recordings", b1 =>
                        {
                            b1.Property<Guid>("VideoCallId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("RecordedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VideoCallId", "__synthesizedOrdinal");

                            b1.ToTable("video_calls", "collaboration");

                            b1.ToJson("Recordings");

                            b1.WithOwner()
                                .HasForeignKey("VideoCallId");
                        });

                    b.Navigation("Participants");

                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.Whiteboard", b =>
                {
                    b.HasOne("Libr4.Collaboration.Domain.CollaborationRoom", null)
                        .WithMany("Whiteboards")
                        .HasForeignKey("CollaborationRoomId");

                    b.OwnsMany("Libr4.Collaboration.Domain.DrawingElement", "Elements", b1 =>
                        {
                            b1.Property<Guid>("WhiteboardId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<double>("Height")
                                .HasColumnType("double precision");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("StrokeWidth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Text")
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision");

                            b1.Property<double>("X")
                                .HasColumnType("double precision");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision");

                            b1.HasKey("WhiteboardId", "__synthesizedOrdinal");

                            b1.ToTable("whiteboards", "collaboration");

                            b1.ToJson("Elements");

                            b1.WithOwner()
                                .HasForeignKey("WhiteboardId");
                        });

                    b.OwnsOne("Libr4.Collaboration.Domain.DrawingToolState", "CurrentToolState", b1 =>
                        {
                            b1.Property<Guid>("WhiteboardId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CurrentTool")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Opacity")
                                .HasColumnType("integer");

                            b1.Property<string>("StrokeWidth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WhiteboardId");

                            b1.ToTable("whiteboards", "collaboration");

                            b1.ToJson("CurrentToolState");

                            b1.WithOwner()
                                .HasForeignKey("WhiteboardId");
                        });

                    b.Navigation("CurrentToolState")
                        .IsRequired();

                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Libr4.Collaboration.Domain.CollaborationRoom", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("VideoCalls");

                    b.Navigation("Whiteboards");
                });
#pragma warning restore 612, 618
        }
    }
}
