<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libr4.Payments.Domain\Libr4.Payments.Domain.csproj" />
    <ProjectReference Include="..\Libr4.Payments.Domain.TaxManagement.FSharp\Libr4.Payments.Domain.TaxManagement.FSharp.fsproj" />
    <ProjectReference Include="..\..\..\Shared\Libr4.Shared.Kernel\Libr4.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\Libr4.Shared.Contracts\Libr4.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
