// <auto-generated />
using System;
using System.Collections.Generic;
using Libr4.Social.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Libr4.Social.Infrastructure.Migrations
{
    [DbContext(typeof(SocialDbContext))]
    [Migration("20260514060951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Libr4.Social.Domain.Network.SocialNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("Followers")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<List<Guid>>("Following")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SocialNetworks");
                });

            modelBuilder.Entity("Libr4.Social.Domain.Network.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SocialNetworkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocialNetworkId");

                    b.ToTable("UserActivity");
                });

            modelBuilder.Entity("Libr4.Social.Domain.Network.SocialNetwork", b =>
                {
                    b.OwnsMany("Libr4.Social.Domain.Network.SocialConnection", "Connections", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ConnectedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ConnectedUserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<string>("Note")
                                .HasColumnType("text");

                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SocialNetworkId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("SocialNetworkId");

                            b1.ToTable("SocialConnection");

                            b1.WithOwner()
                                .HasForeignKey("SocialNetworkId");
                        });

                    b.OwnsMany("Libr4.Social.Domain.Network.UserPost", "Posts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("AttachmentUrls")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("character varying(5000)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.PrimitiveCollection<List<Guid>>("Likes")
                                .IsRequired()
                                .HasColumnType("uuid[]");

                            b1.Property<Guid>("SocialNetworkId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("Tags")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("Id");

                            b1.HasIndex("SocialNetworkId");

                            b1.ToTable("UserPost");

                            b1.WithOwner()
                                .HasForeignKey("SocialNetworkId");

                            b1.OwnsMany("Libr4.Social.Domain.Network.PostComment", "Comments", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("AuthorId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Guid>("UserPostId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserPostId");

                                    b2.ToTable("PostComment");

                                    b2.WithOwner()
                                        .HasForeignKey("UserPostId");
                                });

                            b1.OwnsMany("Libr4.Social.Domain.Network.PostShare", "Shares", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<string>("PersonalMessage")
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("SharedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("SharedByUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("UserPostId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("UserPostId");

                                    b2.ToTable("PostShare");

                                    b2.WithOwner()
                                        .HasForeignKey("UserPostId");
                                });

                            b1.Navigation("Comments");

                            b1.Navigation("Shares");
                        });

                    b.OwnsOne("Libr4.Social.Domain.Network.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("SocialNetworkId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bio")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("Location")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("ProfileImageUrl")
                                .HasColumnType("text");

                            b1.HasKey("SocialNetworkId");

                            b1.ToTable("SocialNetworks");

                            b1.WithOwner()
                                .HasForeignKey("SocialNetworkId");
                        });

                    b.Navigation("Connections");

                    b.Navigation("Posts");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Libr4.Social.Domain.Network.UserActivity", b =>
                {
                    b.HasOne("Libr4.Social.Domain.Network.SocialNetwork", null)
                        .WithMany("ActivityFeed")
                        .HasForeignKey("SocialNetworkId");
                });

            modelBuilder.Entity("Libr4.Social.Domain.Network.SocialNetwork", b =>
                {
                    b.Navigation("ActivityFeed");
                });
#pragma warning restore 612, 618
        }
    }
}
