<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Ops.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libr4.AI.Domain.RAGSearch.FSharp\Libr4.AI.Domain.RAGSearch.FSharp.fsproj" />
  </ItemGroup>

</Project>
