namespace Libr4.IDE.Application.AutonomousAppGeneration.Services.Templates;

/// <summary>
/// P1-8 of audit roadmap. Centralised parameterised templates for fallback artefacts.
/// Each template is a Scriban template; bind via <see cref="IFallbackArtefactTemplateEngine"/>.
/// New stacks add a single template here without touching LlmCodeGenerationService.
/// </summary>
public static class FallbackArtefactTemplates
{
    /// <summary>Generic README cross-stack.</summary>
    public const string Readme =
        """
        # {{ app_name }}

        Generated by Libr4 AutonomousAppGeneration.

        ## Quick start

        Stack: **{{ stack }}** ({{ language }} / {{ framework }})

        {{ if stack == "dotnet" }}
        - `dotnet restore`
        - `dotnet run --project src`
        - `dotnet test`
        {{ else if stack == "python" }}
        - `pip install -r requirements.txt`
        - `uvicorn main:app --host 0.0.0.0 --port {{ port }}`
        - `pytest`
        {{ else if stack == "node" }}
        - `npm install`
        - `node index.js`
        - `npm test`
        {{ end }}

        ## Configuration

        - `PORT`: HTTP port (default {{ port }})
        - `DATABASE_URL`: connection string for {{ database }}
        """;

    /// <summary>Per-stack `.env.example`.</summary>
    public const string EnvExample =
        """
        APP_NAME={{ app_name }}
        PORT={{ port }}
        LOG_LEVEL=INFO
        {{ if stack == "dotnet" }}ASPNETCORE_ENVIRONMENT=Development
        ConnectionStrings__DefaultConnection=Host=localhost;Database=app;Username=app;Password=app
        {{ else if stack == "python" }}DATABASE_URL=postgresql://app:app@db:5432/app
        REDIS_URL=redis://redis:6379/0
        {{ else }}NODE_ENV=development
        DATABASE_URL=postgresql://app:app@db:5432/app
        {{ end }}
        """;

    /// <summary>docker-compose template.</summary>
    public const string DockerCompose =
        """
        version: '3.9'
        services:
          app:
            build: .
            environment:
              - PORT={{ port }}
              {{ if stack == "dotnet" }}- ASPNETCORE_ENVIRONMENT=Production
              - ConnectionStrings__DefaultConnection=Host=db;Database=app;Username=app;Password=app{{ end }}
              {{ if stack == "python" }}- DATABASE_URL=postgresql://app:app@db:5432/app{{ end }}
              {{ if stack == "node" }}- NODE_ENV=production{{ end }}
            ports:
              - "{{ port }}:{{ port }}"
            depends_on:
              - db
          db:
            image: postgres:15
            environment:
              - POSTGRES_USER=app
              - POSTGRES_PASSWORD=app
              - POSTGRES_DB=app
        """;

    /// <summary>GitHub Actions CI template.</summary>
    public const string CiWorkflow =
        """
        name: ci
        on:
          push:
          pull_request:
        jobs:
          test:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v4
              {{ if stack == "dotnet" }}- uses: actions/setup-dotnet@v4
                with:
                  dotnet-version: '8.0'
              - run: dotnet restore
              - run: dotnet test --no-restore{{ end }}
              {{ if stack == "python" }}- uses: actions/setup-python@v5
                with:
                  python-version: '3.12'
              - run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - run: pytest{{ end }}
              {{ if stack == "node" }}- uses: actions/setup-node@v4
                with:
                  node-version: '20'
              - run: npm ci
              - run: npm test{{ end }}
        """;

    /// <summary>SECURITY.md baseline.</summary>
    public const string SecurityBaseline =
        """
        # Security Baseline — {{ app_name }}

        ## Authentication
        - JWT-based auth where applicable, secrets via environment variables.
        - No hardcoded secrets.

        ## Encryption
        - TLS 1.2+ for inbound traffic.
        - Data-at-rest via {{ database }} native encryption.

        ## Headers
        - X-Content-Type-Options: nosniff
        - X-Frame-Options: DENY
        - Content-Security-Policy: default-src 'self'

        ## Dependencies
        - Renovate / Dependabot updates enabled in CI.
        - Static security scan in pipeline (CodeQL / Trivy).
        """;

    /// <summary>Observability baseline.</summary>
    public const string ObservabilityBaseline =
        """
        # Observability Baseline — {{ app_name }}

        ## Structured logging
        - JSON output on stdout
        - Required fields: event, request_id, method, path, status_code, duration_ms

        ## Correlation
        - Accept and propagate `X-Request-ID` header
        - Surface request id in every log line

        ## Health endpoints
        - `GET /health` — process liveness, no dependencies
        - `GET /readiness` — checks {{ database }} connectivity, returns 503 on failure

        ## Metrics
        - Counter: requests_total{method, path, status_code}
        - Histogram: request_duration_ms{method, path}
        """;
}
