namespace Libr4.Shared.Contracts.Templates;

/// <summary>
/// Schema for code fragment generation.
/// Similar to Fragments' fragmentSchema but adapted for C#.
/// </summary>
public record CodeFragmentSchema
{
    /// <summary>
    /// Commentary describing what the fragment does and the steps taken.
    /// </summary>
    public string Commentary { get; init; } = string.Empty;

    /// <summary>
    /// Name of the template used to generate the fragment.
    /// </summary>
    public string Template { get; init; } = string.Empty;

    /// <summary>
    /// Short title of the fragment. Max 3 words.
    /// </summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>
    /// Short description of the fragment. Max 1 sentence.
    /// </summary>
    public string Description { get; init; } = string.Empty;

    /// <summary>
    /// Additional dependencies required by the fragment.
    /// Does not include dependencies already in the template.
    /// </summary>
    public List<string> AdditionalDependencies { get; init; } = new();

    /// <summary>
    /// Whether the fragment requires additional dependencies.
    /// </summary>
    public bool HasAdditionalDependencies { get; init; }

    /// <summary>
    /// Command to install additional dependencies.
    /// </summary>
    public string InstallDependenciesCommand { get; init; } = string.Empty;

    /// <summary>
    /// Port number used by the fragment (null if no ports exposed).
    /// </summary>
    public int? Port { get; init; }

    /// <summary>
    /// Relative path to the file, including the file name.
    /// </summary>
    public string FilePath { get; init; } = string.Empty;

    /// <summary>
    /// Code generated by the fragment. Only runnable code is allowed.
    /// </summary>
    public string Code { get; init; } = string.Empty;

    /// <summary>
    /// Language of the generated code.
    /// </summary>
    public string Language { get; init; } = string.Empty;

    /// <summary>
    /// Whether the code is valid and runnable.
    /// </summary>
    public bool IsValid { get; init; } = true;

    /// <summary>
    /// Error message if the fragment is not valid.
    /// </summary>
    public string? Error { get; init; }

    /// <summary>
    /// Additional metadata about the fragment.
    /// </summary>
    public Dictionary<string, string> Metadata { get; init; } = new();
}

/// <summary>
/// Schema for Morph-based code editing.
/// Token-efficient editing using special markers.
/// </summary>
public record MorphEditSchema
{
    /// <summary>
    /// Explanation of what changes are being made and why.
    /// </summary>
    public string Commentary { get; init; } = string.Empty;

    /// <summary>
    /// One-line instruction on what the change is.
    /// </summary>
    public string Instruction { get; init; } = string.Empty;

    /// <summary>
    /// The edit with special markers for unchanged code.
    /// Use "// ... existing code ..." to represent unchanged code.
    /// </summary>
    public string Edit { get; init; } = string.Empty;

    /// <summary>
    /// Path to the file being edited.
    /// </summary>
    public string FilePath { get; init; } = string.Empty;

    /// <summary>
    /// Whether the edit is valid.
    /// </summary>
    public bool IsValid { get; init; } = true;

    /// <summary>
    /// Error message if the edit is not valid.
    /// </summary>
    public string? Error { get; init; }
}

/// <summary>
/// Validator for code fragment schemas.
/// </summary>
public class CodeFragmentSchemaValidator
{
    /// <summary>
    /// Validates a code fragment schema.
    /// </summary>
    public (bool IsValid, List<string> Errors) Validate(CodeFragmentSchema fragment)
    {
        var errors = new List<string>();

        if (string.IsNullOrWhiteSpace(fragment.Commentary))
            errors.Add("Commentary is required");

        if (string.IsNullOrWhiteSpace(fragment.Template))
            errors.Add("Template is required");

        if (string.IsNullOrWhiteSpace(fragment.Title))
            errors.Add("Title is required");
        else if (fragment.Title.Split(' ').Length > 3)
            errors.Add("Title should be max 3 words");

        if (string.IsNullOrWhiteSpace(fragment.Description))
            errors.Add("Description is required");

        if (string.IsNullOrWhiteSpace(fragment.FilePath))
            errors.Add("FilePath is required");

        if (string.IsNullOrWhiteSpace(fragment.Code))
            errors.Add("Code is required");

        if (fragment.HasAdditionalDependencies)
        {
            if (string.IsNullOrWhiteSpace(fragment.InstallDependenciesCommand))
                errors.Add("InstallDependenciesCommand is required when HasAdditionalDependencies is true");
        }

        if (fragment.AdditionalDependencies.Count == 0 && fragment.HasAdditionalDependencies)
            errors.Add("AdditionalDependencies should not be empty when HasAdditionalDependencies is true");

        return (errors.Count == 0, errors);
    }

    /// <summary>
    /// Validates a morph edit schema.
    /// </summary>
    public (bool IsValid, List<string> Errors) Validate(MorphEditSchema edit)
    {
        var errors = new List<string>();

        if (string.IsNullOrWhiteSpace(edit.Commentary))
            errors.Add("Commentary is required");

        if (string.IsNullOrWhiteSpace(edit.Instruction))
            errors.Add("Instruction is required");

        if (string.IsNullOrWhiteSpace(edit.Edit))
            errors.Add("Edit is required");

        if (string.IsNullOrWhiteSpace(edit.FilePath))
            errors.Add("FilePath is required");

        // Check for proper edit format
        if (!edit.Edit.Contains("// ... existing code ..."))
            errors.Add("Edit should contain '// ... existing code ...' markers for unchanged code");

        return (errors.Count == 0, errors);
    }
}

/// <summary>
/// Generator for system prompts based on templates.
/// </summary>
public class FragmentPromptGenerator
{
    /// <summary>
    /// Generates a system prompt for code fragment generation.
    /// </summary>
    public string GenerateSystemPrompt(IReadOnlyList<SandboxTemplate> templates)
    {
        var templatesPrompt = new InMemorySandboxTemplateRegistry().TemplatesToPrompt(templates);

        return $@"
You are a skilled software engineer.
You do not make mistakes.
Generate a code fragment.
You can install additional dependencies.
Do not touch project dependencies files like package.json, package-lock.json, requirements.txt, etc.
Do not wrap code in backticks.
Always break the lines correctly.
You can use one of the following templates:
{templatesPrompt}
";
    }

    /// <summary>
    /// Generates a system prompt for Morph-based editing.
    /// </summary>
    public string GenerateMorphSystemPrompt()
    {
        return @"
You are a code editing specialist.
You make precise, minimal edits to existing code.
Use the special marker '// ... existing code ...' to represent unchanged code.
Be lazy when outputting code - rely heavily on existing code comments.
Each edit should contain minimally sufficient context of unchanged lines around the code.
DO NOT omit spans of pre-existing code without using the '// ... existing code ...' marker.
If you plan on deleting a section, provide context before and after to delete it.
";
    }
}
